"""SYNTHETIC_TEST_ONLY: genuine persisted pipeline, no provider or production DB.

Wire records are generated by the actual charged transport with a fake HTTP
opener. Manager entries are synthetic and cannot authenticate an invocation.
"""
import base64
import copy
from contextlib import ExitStack
from dataclasses import replace
import json
from pathlib import Path
import sqlite3
from tests import legacy_null_pass
import unittest
from unittest.mock import patch

from desk import paper_terminal_reconciliation as r, paper_cycle as cycle
from desk import paper_read_sources as transport, provider_pacing
from desk.model import canonical,digest
from desk.paper_observe_cli import observe
from desk.ownership_acquisition import _Setup
from tests import test_paper_cycle as fixtures
from tests.test_paper_read_sources import Response


def dump(path):
    with sqlite3.connect(path) as c:return list(c.iterdump())


class TerminalReconciliationTests(unittest.TestCase):
    def setUp(self):
        legacy_null_pass.install(self)    # T22: these tests certify retained pre-T22 NULL/unresolved states
        self.h=fixtures.PaperCycleTests();self.h.setUp();self.addCleanup(self.h.doCleanups)
        self.f=self.h.f;self.store=self.f.progress.store;self.progress=self.f.progress
        self.cfg=self.h.cfg;self.ledger=self.h.path;self.target=self.h.target
        _Setup(self.store,self.f.jobs.descriptor(self.target.scan_id),self.progress.admission(self.target.scan_id))
        self.f.protocol.lp_supply=100
        self.policy=Path(self.f.tmp.name)/'terminal-policy.json'
        self.policy.write_text(canonical({'version':1,'associations':[]}))
        self.patcher=patch.object(r,'POLICY',self.policy);self.patcher.start();self.addCleanup(self.patcher.stop)
        self.calls=[];self.sources=[];self.mint_control=None;self.break_transport=False
        outer=self
        class Opener:
            def open(self,request,*,timeout):
                call=json.loads(request.data);outer.calls.append(call)
                if outer.break_transport:raise OSError('synthetic ambiguous transport')
                method,params=call['method'],call['params']
                if method=='getAccountInfo' and params[0]==outer.target.mint:
                    value={'context':{'slot':100},'value':outer.f.protocol.rpc('getMultipleAccounts',[])['value'][6]}
                    if outer.mint_control is not None:
                        raw=bytearray(base64.b64decode(value['value']['data'][0]));offset=outer.mint_control
                        raw[offset:offset+4]=(1).to_bytes(4,'little');raw[offset+4:offset+36]=b'x'*32
                        value['value']['data'][0]=base64.b64encode(raw).decode()
                else:value=outer.f.protocol.rpc(method,params)
                return Response(canonical({'id':transport.RPC_ID,'jsonrpc':'2.0','result':value}).encode())
        self.opener=Opener()
        self.pacing=Path(self.f.tmp.name)/'pacing.sqlite';provider_pacing.initialize(self.pacing)

    def run_cycle(self,*,legacy=False,candidates=None):
        outer=self
        class Legacy(transport.PaperReadSources):
            def __init__(self,*a,**kw):super().__init__(*a,**kw);outer.sources.append(self)
        def factory(*a,**kw):
            source=transport.PaperReadSources(*a,**kw);outer.sources.append(source);return source
        # Exact default type is deliberately needed for automatic intrinsic
        # closure. A wrapper without complete association must remain pending.
        source_factory=Legacy if legacy else factory
        with ExitStack() as stack:
            stack.enter_context(patch.dict(transport.os.environ,{'HELIUS_API_KEY':'SYNTHETIC_TEST_ONLY'},clear=True))
            stack.enter_context(patch.object(transport,'build_opener',return_value=self.opener))
            stack.enter_context(patch.object(transport.time,'time',return_value=self.f.at))
            stack.enter_context(patch.object(transport.time,'monotonic',return_value=1))
            return self.h.run_cycle(source_factory=source_factory,candidates=(self.h.item,) if candidates is None else candidates)

    def legacy(self):
        for _ in range(7):self.assertTrue(self.progress.reserve(self.target.scan_id))
        result=self.run_cycle(legacy=True)
        self.assertEqual(result['blockers'],['SOURCE_CONTENT_REJECTED'],result)
        self.assertEqual(len(self.calls),3)
        refs=tuple(self.sources[0].attempt_evidence_refs)
        identity=result['pass_id']
        with self.store.connect() as c:
            key=c.execute('SELECT intent_hash FROM paper_observation_passes WHERE id=?',(identity,)).fetchone()[0]
        intent=self.store.load(key)
        for k in ('terminal_context','ledger_anchors','source_hash'):intent.pop(k,None)
        key=self.store.save(intent)
        with self.store.connect() as c:c.execute('UPDATE paper_observation_passes SET intent_hash=? WHERE id=?',(key,identity))
        outcome={k:v for k,v in result.items() if k not in ('pass_id','intent_hash','attempt_refs','terminal_hazards','evidence_hash','terminal_receipt_hash')}
        outcome_hash=self.store.save(outcome)
        unit='synthetic-terminal-test.service';invocation='a'*32;at=self.f.at
        start=f'Started {unit} - /synthetic/python tools/history_first_paper_entry.py --config /synthetic/config --research-db {self.f.jobs.path} --evidence-db {self.store.path} --ledger-db {self.ledger} --targets /synthetic/targets --execute'
        messages=[start,unit+': Main process exited, code=exited, status=2/INVALIDARGUMENT',unit+": Failed with result 'exit-code'.",unit+': Consumed synthetic CPU time.']
        entries=[{'MESSAGE':m,'__REALTIME_TIMESTAMP':str((at-1 if i==0 else at+1)*1_000_000+i),'_SYSTEMD_UNIT':'init.scope','UNIT':unit,'INVOCATION_ID':invocation} for i,m in enumerate(messages)]
        entries[0]['JOB_RESULT']='done'
        self.args=dict(pass_id=identity,outcome_hash=outcome_hash,attempt_refs=refs,invocation_hash=self.store.save(entries),pacing_db=self.pacing)
        self.pin=r.plan(self.f.jobs.path,self.store.path,self.ledger,self.cfg,**self.args)
        return self.pin

    def approve(self,pin=None):
        self.policy.write_text(canonical({'version':1,'associations':[self.pin if pin is None else pin]}))

    def reconcile(self,**kw):
        return r.reconcile(self.f.jobs.path,self.store.path,self.ledger,self.cfg,**(self.args|kw))

    def gate(self,scan=None):
        return r.gate(self.store,self.f.jobs.path,() if scan is None else (scan,))

    def test_legacy_requires_exact_review_pin_original_null_and_charges_preserved(self):
        self.legacy();before_e=dump(self.store.path);before_l=dump(self.ledger);before_j=dump(self.f.jobs.path)
        with self.assertRaisesRegex(ValueError,'not explicitly reviewed'):self.reconcile()
        self.assertEqual(dump(self.store.path),before_e)
        self.assertEqual(self.gate(),'OBSERVATION_RECOVERY_REQUIRED')
        self.approve();result=self.reconcile();self.assertEqual(result['status'],'RECORDED')
        self.assertFalse(result['entry_authorized']);self.assertEqual(self.reconcile()['status'],'ALREADY_RECORDED')
        self.assertEqual(dump(self.ledger),before_l);self.assertEqual(dump(self.f.jobs.path),before_j)
        with self.store.connect() as c:
            self.assertEqual(c.execute('SELECT intent_hash,outcome_hash FROM paper_observation_passes WHERE id=?',(self.args['pass_id'],)).fetchone(),(self.pin['intent_hash'],None))
        self.assertEqual(self.progress.admission(self.target.scan_id)['requests_used'],10)
        self.assertIsNone(self.gate());self.assertEqual(self.gate(self.target.scan_id),'REJECTED_SCAN_RETIRED')
        self.assertEqual(self.run_cycle()['blockers'],['REJECTED_SCAN_RETIRED']);self.assertEqual(len(self.calls),3)
        result=observe(self.f.jobs.path,self.store.path,candidates=(self.target,))
        self.assertEqual(result['stopped_reason'],'REJECTED_SCAN_RETIRED');self.assertEqual(len(self.calls),3)

    def test_future_known_rejection_certifies_intrinsic_without_policy_or_retry(self):
        result=self.run_cycle();self.assertEqual(result['blockers'],['SOURCE_CONTENT_REJECTED'])
        self.assertIn('terminal_receipt_hash',result,result);self.assertEqual(len(result['attempt_refs']),3)
        self.assertEqual(result['terminal_hazards'],['OUTSTANDING_WITHDRAWABLE_LP_SUPPLY'])
        self.assertEqual(len(self.calls),3);self.assertEqual(self.gate(self.target.scan_id),'REJECTED_SCAN_RETIRED')
        self.assertEqual(self.run_cycle()['blockers'],['REJECTED_SCAN_RETIRED']);self.assertEqual(len(self.calls),3)
        # A different admitted scan passes the shared pre-I/O gate. It does not
        # retry the rejected scan or borrow its allowance.
        source=self.f.jobs.source(self.target.scan_id)
        report={'mint':self.target.mint,'eligible_for_trading':False,'calls':3};report['report_hash']=digest(report)
        source.update(status='COMPLETE',result=canonical(report))
        admission=self.progress.admission(self.target.scan_id)
        self.progress.prepare_source(self.target.scan_id,admission['descriptor_hash'],source)
        self.progress.seal_source(self.target.scan_id,admission['descriptor_hash'],digest(source))
        with self.f.jobs.connect() as c:c.execute("UPDATE scans SET status='COMPLETE',result=? WHERE id=?",(source['result'],self.target.scan_id))
        other=self.f.target()
        self.assertIsNone(self.gate(other.scan_id))
        self.assertEqual(self.progress.admission(self.target.scan_id)['requests_used'],3)
        self.assertEqual(self.progress.admission(other.scan_id)['requests_used'],0)
        _Setup(self.store,self.f.jobs.descriptor(other.scan_id),self.progress.admission(other.scan_id))
        second=self.run_cycle(candidates=(replace(self.h.item,target=other),))
        self.assertEqual(second['blockers'],['SOURCE_CONTENT_REJECTED']);self.assertIn('terminal_receipt_hash',second)
        self.assertEqual(len(self.calls),6)
        self.assertEqual(self.progress.admission(other.scan_id)['requests_used'],3)

    def test_unknown_content_and_crash_do_not_certify(self):
        self.f.protocol.raw+=b'unknown'
        result=self.run_cycle();self.assertNotIn('terminal_receipt_hash',result)
        self.assertEqual(self.gate(),'OBSERVATION_RECOVERY_REQUIRED')
        count=len(self.calls);self.assertEqual(self.run_cycle()['blockers'],['OBSERVATION_RECOVERY_REQUIRED'])
        self.assertEqual(len(self.calls),count)

    def test_missing_duplicate_reordered_and_failed_attempts_refuse_without_mutation(self):
        self.legacy();self.approve();before=dump(self.store.path)
        variants=[self.args['attempt_refs'][:2],self.args['attempt_refs'][::-1],(self.args['attempt_refs'][0],)*3]
        for refs in variants:
            with self.subTest(refs=refs),self.assertRaises((ValueError,IndexError)):self.reconcile(attempt_refs=refs)
            self.assertEqual(dump(self.store.path),before)
        record=copy.deepcopy(self.store.load(self.args['attempt_refs'][1]));record['failure_code']='TRANSPORT_ERROR'
        refs=list(self.args['attempt_refs']);refs[1]=self.store.save(record);changed=dump(self.store.path)
        with self.assertRaises(ValueError):self.reconcile(attempt_refs=refs)
        self.assertEqual(dump(self.store.path),changed)

    def test_changed_ledger_budget_invocation_and_pending_transport_refuse(self):
        self.legacy();self.approve();before=dump(self.store.path)
        with sqlite3.connect(self.ledger) as c:old=c.execute('SELECT payload FROM state').fetchone()[0]
        with sqlite3.connect(self.ledger) as c:
            state=json.loads(c.execute('SELECT payload FROM state').fetchone()[0]);state['cash']='4'
            c.execute('UPDATE state SET payload=?',(canonical(state),))
        changed_ledger=dump(self.ledger)
        with self.assertRaises(ValueError):self.reconcile()
        self.assertEqual(dump(self.ledger),changed_ledger);self.assertEqual(dump(self.store.path),before)
        with sqlite3.connect(self.ledger) as c:c.execute('UPDATE state SET payload=?',(old,))  # synthetic scratch only
        witness=self.store.load(self.args['invocation_hash']);witness[1]['MESSAGE']='synthetic crash, no known exit'
        wrong=self.store.save(witness);changed=dump(self.store.path)
        with self.assertRaises(ValueError):self.reconcile(invocation_hash=wrong)
        self.assertEqual(dump(self.store.path),changed)
        self.progress.reserve(self.target.scan_id);changed=dump(self.store.path)
        with self.assertRaisesRegex(ValueError,'shape|charges|admission'):self.reconcile()
        self.assertEqual(dump(self.store.path),changed)

    def test_pacing_pending_refuses_and_does_not_finish_ticket(self):
        self.legacy();self.approve()
        with sqlite3.connect(self.pacing) as c:c.execute("UPDATE state SET pending=? WHERE provider='helius'",('b'*32,))
        before=dump(self.store.path);pacing=dump(self.pacing)
        with self.assertRaisesRegex(ValueError,'pending'):self.reconcile()
        self.assertEqual(dump(self.store.path),before);self.assertEqual(dump(self.pacing),pacing)

    def test_other_pending_pass_not_exempted_and_immutable_guard_validation(self):
        self.legacy();self.approve();self.reconcile()
        with self.store.connect() as c:
            c.execute('INSERT INTO paper_observation_passes VALUES(?,?,NULL)',('c'*32,self.pin['intent_hash']))
        self.assertEqual(self.gate(),'OBSERVATION_RECOVERY_REQUIRED')
        with self.store.connect() as c:
            with self.assertRaises(sqlite3.IntegrityError):c.execute(f'UPDATE {r.TABLE} SET payload=payload')
            c.execute(f'DROP TRIGGER {r.TABLE}_update')
            c.execute(f"CREATE TRIGGER {r.TABLE}_update BEFORE UPDATE ON {r.TABLE} BEGIN SELECT 1; END")
        with self.assertRaisesRegex(ValueError,'guards'):self.gate()

    def test_scalar_payload_preflight_before_parser_and_partial_schema_refusal(self):
        self.legacy();self.approve();self.reconcile()
        with self.store.connect() as c:
            c.execute(f'DROP TRIGGER {r.TABLE}_update')
            c.execute(f'UPDATE {r.TABLE} SET payload=?',('x'*(r.MAX_BYTES+1),))
            c.execute(r._guards()[r.TABLE+'_update'])
        with patch.object(r.runtime,'_parse',side_effect=AssertionError('must not materialize')):
            with self.assertRaisesRegex(ValueError,'scalar bound'):self.gate()

    def test_transaction_rollback_preserves_originals(self):
        self.legacy();self.approve();before=dump(self.store.path)
        original=r._insert
        def crash(c,v):original(c,v);raise RuntimeError('synthetic crash after append')
        with patch.object(r,'_insert',side_effect=crash):
            with self.assertRaises(RuntimeError):self.reconcile()
        self.assertEqual(dump(self.store.path),before);self.assertEqual(self.gate(),'OBSERVATION_RECOVERY_REQUIRED')

    def test_intrinsic_binding_tampering_refuses_both_consumers(self):
        result=self.run_cycle();self.assertIn('terminal_receipt_hash',result)
        with self.store.connect() as c:
            c.execute('UPDATE paper_observation_passes SET intent_hash=? WHERE id=?',('0'*64,result['pass_id']))
        self.assertEqual(self.run_cycle()['blockers'],['OBSERVATION_RECOVERY_REQUIRED'])
        self.assertEqual(observe(self.f.jobs.path,self.store.path,candidates=(self.target,))['stopped_reason'],'OBSERVATION_RECOVERY_REQUIRED')
        self.assertEqual(len(self.calls),3)

    def test_active_mint_authority_is_intrinsic_one_charge_terminal_rejection(self):
        self.mint_control=0
        result=self.run_cycle()
        self.assertEqual(result['terminal_hazards'],['ACTIVE_MINT_AUTHORITY'])
        self.assertIn('terminal_receipt_hash',result)
        self.assertEqual(len(result['attempt_refs']),1);self.assertEqual(len(self.calls),1)
        self.assertEqual(self.progress.admission(self.target.scan_id)['requests_used'],1)
        self.assertEqual(self.gate(self.target.scan_id),'REJECTED_SCAN_RETIRED')

    def test_active_freeze_authority_is_one_charge_rejection(self):
        self.mint_control=46
        result=self.run_cycle()
        self.assertEqual(result['terminal_hazards'],['ACTIVE_FREEZE_AUTHORITY'])
        self.assertIn('terminal_receipt_hash',result);self.assertEqual(len(self.calls),1)

    def test_text_matching_generic_error_is_not_terminal_classification(self):
        from desk.live_observation import ObservationError
        with patch('desk.paper_observation_collector.ingest_mint',side_effect=ObservationError('Unsafe pool: OUTSTANDING_WITHDRAWABLE_LP_SUPPLY')):
            result=self.run_cycle()
        self.assertNotIn('terminal_hazards',result);self.assertNotIn('terminal_receipt_hash',result)
        self.assertEqual(self.gate(),'OBSERVATION_RECOVERY_REQUIRED')

    def test_failed_transport_retains_charge_and_stays_globally_blocked(self):
        self.break_transport=True
        result=self.run_cycle();self.assertEqual(result['blockers'],['SOURCE_REQUEST_FAILED'])
        self.assertNotIn('terminal_receipt_hash',result)
        self.assertEqual(self.progress.admission(self.target.scan_id)['requests_used'],1)
        self.assertEqual(self.gate(),'OBSERVATION_RECOVERY_REQUIRED')
        record=self.store.load(self.sources[0].attempt_evidence_refs[0])
        self.assertIsNotNone(record['failure_code']);self.assertEqual(len(self.calls),1)

    def test_receipt_insert_replace_cannot_overwrite_original(self):
        self.legacy();self.approve();self.reconcile();before=dump(self.store.path)
        with self.store.connect() as c:
            with self.assertRaises(sqlite3.IntegrityError):
                c.execute(f'INSERT OR REPLACE INTO {r.TABLE} VALUES(?,?,?,?)',(self.pin['pass_id'],self.pin['scan_id'],canonical(self.pin),'0'*64))
        self.assertEqual(dump(self.store.path),before)

    def test_final_ledger_write_before_append_conflict_refuses(self):
        self.legacy();self.approve();before=dump(self.store.path)
        original=r.plan;calls=[]
        def changed(*a,**kw):
            value=original(*a,**kw);calls.append(1)
            if len(calls)==2:value=dict(value,source_hash='0'*64)
            return value
        with patch.object(r,'plan',side_effect=changed):
            with self.assertRaisesRegex(ValueError,'changed before append'):self.reconcile()
        self.assertEqual(dump(self.store.path),before)

    def test_existing_monitoring_grant_is_verified_and_preserved(self):
        from desk.monitoring_budget import MonitoringBudget
        budget=MonitoringBudget(self.store,self.ledger,self.cfg,clock=lambda:self.f.at)
        budget.provision()
        self.legacy();self.approve();before=dump(self.store.path)
        with self.store.connect() as c:
            original=c.execute('SELECT * FROM paper_monitoring_budget').fetchall()
        self.reconcile()
        with self.store.connect() as c:
            self.assertEqual(c.execute('SELECT * FROM paper_monitoring_budget').fetchall(),original)
        self.assertIsNone(self.gate())
        # Corrupt supplied accounting is never ignored because this is a
        # candidate pass rather than a positions-only monitoring pass.
        with self.store.connect() as c:c.execute("UPDATE paper_monitoring_budget SET code_hash=?",('0'*64,))
        changed=dump(self.store.path)
        with self.assertRaises(ValueError):self.reconcile()
        self.assertEqual(dump(self.store.path),changed)

    def test_monitoring_unreturned_attempt_remains_blocked(self):
        from desk.monitoring_budget import MonitoringBudget
        MonitoringBudget(self.store,self.ledger,self.cfg,clock=lambda:self.f.at).provision()
        self.legacy();self.approve()
        with self.store.connect() as c:
            c.execute('INSERT INTO paper_monitoring_reservations VALUES(?,?,?,?,?,?,?)',(1,self.f.at,self.target.scan_id,self.target.mint,'0'*64,'getAccountInfo','1'*64))
        before=dump(self.store.path)
        with self.assertRaisesRegex(ValueError,'unresolved'):self.reconcile()
        self.assertEqual(dump(self.store.path),before)

    def test_hash_shape_is_rejected_before_any_receipt_parser(self):
        self.legacy();self.approve();self.reconcile()
        with self.store.connect() as c:
            c.execute(f'DROP TRIGGER {r.TABLE}_update')
            c.execute(f'UPDATE {r.TABLE} SET payload_hash=?',(b'0'*64,))
            c.execute(r._guards()[r.TABLE+'_update'])
        with patch.object(r.runtime,'_parse',side_effect=AssertionError('must not materialize')):
            with self.assertRaisesRegex(ValueError,'scalar bound'):self.gate()

    def test_locked_read_only_plan_is_not_authorization(self):
        self.legacy();before_e=dump(self.store.path);before_l=dump(self.ledger)
        self.assertEqual(r.review_plan(self.f.jobs.path,self.store.path,self.ledger,self.cfg,**self.args),self.pin)
        self.assertEqual(dump(self.store.path),before_e);self.assertEqual(dump(self.ledger),before_l)
        self.assertEqual(self.gate(),'OBSERVATION_RECOVERY_REQUIRED')

    def test_unchanged_public_snapshot_remains_a_known_negative_not_entry_evidence(self):
        from desk.live_observation import ingest_pool,ProviderObservation,PolicyRejection
        p=json.loads((Path(__file__).resolve().parents[1]/'fixtures/mainnet-pool-fee-snapshot.json').read_text())
        original=canonical(p)
        with self.assertRaises(PolicyRejection) as caught:
            ingest_pool(lambda:ProviderObservation('PUBLIC_CAPTURE_OFFLINE_REPLAY',0,p['capture']),
                mint=p['mint'],pool=p['pool'],now=0,token_profile_version=1)
        self.assertIn('BOOST_POOL_UNSUPPORTED',caught.exception.reasons)
        self.assertEqual(canonical(p),original)

    def test_actual_history_first_wrapper_retired_and_unrelated_preflight(self):
        from tools import history_first_paper_entry as tool
        self.legacy();self.approve();self.reconcile()
        with patch.object(tool.cli,'_credentials',side_effect=AssertionError('credentials forbidden')),patch.object(tool.cycle,'_history',side_effect=AssertionError('preparation forbidden')):
            with self.assertRaisesRegex(ValueError,'REJECTED_SCAN_RETIRED'):
                with tool._context(self.f.jobs.path,self.store.path,self.ledger,self.cfg,self.h.item):pass
            source=self.f.jobs.source(self.target.scan_id)
            report={'mint':self.target.mint,'eligible_for_trading':False,'calls':10};report['report_hash']=digest(report)
            source.update(status='COMPLETE',result=canonical(report));admission=self.progress.admission(self.target.scan_id)
            self.progress.prepare_source(self.target.scan_id,admission['descriptor_hash'],source)
            self.progress.seal_source(self.target.scan_id,admission['descriptor_hash'],digest(source))
            with self.f.jobs.connect() as c:c.execute("UPDATE scans SET status='COMPLETE',result=? WHERE id=?",(source['result'],self.target.scan_id))
            other=self.f.target();_Setup(self.store,self.f.jobs.descriptor(other.scan_id),self.progress.admission(other.scan_id))
            before_e=dump(self.store.path);before_l=dump(self.ledger)
            with patch.object(tool.time,'time',return_value=self.f.at):
                with tool._context(self.f.jobs.path,self.store.path,self.ledger,self.cfg,replace(self.h.item,target=other)) as (_,progress):
                    self.assertEqual(progress.admission(other.scan_id)['requests_used'],0)
            self.assertEqual(dump(self.store.path),before_e);self.assertEqual(dump(self.ledger),before_l)
        self.assertEqual(len(self.calls),3)

    def test_missing_original_atomic_capture_is_not_reconstructed_into_evidence(self):
        self.legacy();self.approve()
        records=[self.store.load(k) for k in self.args['attempt_refs']]
        responses=[r._wire(x['response_bytes_base64'],2*1024*1024)['result'] for x in records]
        capture={'kind':'pool_snapshot','discovery':responses[1],'method':records[2]['method'],'params':records[2]['params'],'result':responses[2]}
        key=digest(capture);self.assertEqual(self.store.load(key),capture)
        with self.store.connect() as c:c.execute('DELETE FROM pages WHERE hash=?',(key,))
        before=dump(self.store.path)
        with self.assertRaisesRegex(ValueError,'Evidence missing or oversized'):self.reconcile()
        self.assertEqual(dump(self.store.path),before)
        with self.store.connect() as c:self.assertIsNone(c.execute('SELECT 1 FROM pages WHERE hash=?',(key,)).fetchone())

    def test_proof_sql_preflight_rejects_corrupt_blobs_types_and_raw_bounds_without_fetch(self):
        value={'kind':'SYNTHETIC_BOUNDED_PROOF'};key=self.store.save(value)
        with self.store.connect() as c:original=c.execute('SELECT payload,raw_bytes FROM pages WHERE hash=?',(key,)).fetchone()
        fetched=[]
        class NoPayloadFetch(sqlite3.Connection):
            def execute(connection,sql,*args,**kwargs):
                if sql.startswith('SELECT payload,'):
                    fetched.append(sql);raise AssertionError('Corrupt proof payload was materialized')
                return super().execute(sql,*args,**kwargs)
        # Includes the independent20MiB corrupt compressed blob and invalid
        # raw_bytes reproduction, plus large TEXT metadata and malformed types.
        variants=[(sqlite3.Binary(b'x'*(20*1024*1024)),-1),
                  (sqlite3.Binary(b'x'*(r.MAX_PROOF_COMPRESSED_BYTES+1)),original[1]),
                  ('not a compressed BLOB',original[1]),(original[0],'x'*(20*1024*1024)),
                  (original[0],1.25),(original[0],r.MAX_PROOF_RAW_BYTES+1),(original[0],0)]
        for payload,size in variants:
            with self.subTest(payload_type=type(payload).__name__,raw_type=type(size).__name__):
                with self.store.connect() as c:c.execute('UPDATE pages SET payload=?,raw_bytes=? WHERE hash=?',(payload,size,key))
                connect=lambda:sqlite3.connect(self.store.path,isolation_level=None,factory=NoPayloadFetch)
                with patch.object(self.store,'connect',side_effect=connect),patch.object(self.store,'load',side_effect=AssertionError('unsafe loader')):
                    with self.assertRaisesRegex(ValueError,'scalar shape'):r._load(self.store,key)
        self.assertEqual(fetched,[])

    def test_proof_preflight_and_content_fetch_share_snapshot_during_concurrent_replacement(self):
        value={'kind':'SYNTHETIC_SNAPSHOT_PROOF','retained':'original'};key=self.store.save(value)
        with self.store.connect() as c:c.execute('PRAGMA journal_mode=WAL')
        path=self.store.path;replaced=[]
        class ConcurrentReplacement(sqlite3.Connection):
            def execute(connection,sql,*args,**kwargs):
                cursor=super().execute(sql,*args,**kwargs)
                if sql.startswith('SELECT typeof(hash)'):
                    with sqlite3.connect(path,isolation_level=None) as writer:
                        writer.execute('UPDATE pages SET payload=?,raw_bytes=? WHERE hash=?',(sqlite3.Binary(b'x'*(20*1024*1024)),'corrupt',key))
                    replaced.append(True)
                return cursor
        connect=lambda:sqlite3.connect(path,isolation_level=None,factory=ConcurrentReplacement)
        with patch.object(self.store,'connect',side_effect=connect),patch.object(self.store,'load',side_effect=AssertionError('unsafe loader')):
            self.assertEqual(r._load(self.store,key),value)
        self.assertEqual(replaced,[True])
        with self.assertRaisesRegex(ValueError,'scalar shape'):r._load(self.store,key)

    def test_bounded_proof_decode_still_rejects_trailing_compression_and_checksum_corruption(self):
        import zlib
        value={'kind':'SYNTHETIC_ENCODING_PROOF'};key=self.store.save(value)
        variants=[zlib.compress(canonical(value).encode())+b'trailing',zlib.compress(b'{}'),b'not zlib']
        for payload in variants:
            with self.store.connect() as c:c.execute('UPDATE pages SET payload=? WHERE hash=?',(sqlite3.Binary(payload),key))
            with self.assertRaises(ValueError):r._load(self.store,key)

    def monitoring_fixture(self):
        from tests import test_monitoring_budget as budget_fixtures
        fixture=budget_fixtures.MonitoringBudgetTests();fixture.setUp();self.addCleanup(fixture.doCleanups)
        source=transport.PaperReadSources(fixture.progress,fixture.scan,monitoring_budget=fixture.budget)
        body=canonical({'jsonrpc':'2.0','id':transport.RPC_ID,'result':100}).encode()
        class Opener:
            def open(self,request,*,timeout):return Response(body)
        return fixture,source,Opener()

    def test_reused_monitoring_source_exceeds18_retains_all_outcomes_and_preserves_existing_cap(self):
        fixture,source,opener=self.monitoring_fixture();original=fixture.progress.admission(fixture.scan);refs=[]
        with patch.object(transport.os.environ,'get',return_value='SYNTHETIC_TEST_ONLY'),patch.object(transport,'build_opener',return_value=opener):
            for count in range(1,61):
                _,key=source.rpc_with_evidence('getSlot',[{'commitment':'finalized'}],timeout_seconds=3)
                refs.append(key)
                record=fixture.store.load(key)
                self.assertEqual(record['monitoring_reservation']['total_used'],count)
                self.assertIsNone(record['failure_code'])
                with fixture.store.connect() as c:
                    self.assertEqual(c.execute('SELECT evidence_hash FROM paper_monitoring_outcomes WHERE reservation_id=?',(count,)).fetchone(),(key,))
        self.assertEqual(list(source.attempt_evidence_refs),refs[-18:]);self.assertEqual(len(source.attempt_evidence_refs),18)
        self.assertEqual(fixture.progress.admission(fixture.scan),original)
        with fixture.store.connect() as c:
            self.assertEqual(c.execute('SELECT total,cap,blocked FROM paper_monitoring_budget').fetchone(),(60,60,None))
            self.assertEqual(c.execute('SELECT COUNT(*) FROM paper_monitoring_outcomes').fetchone()[0],60)
            self.assertIsNone(c.execute('SELECT 1 FROM paper_monitoring_reservations r LEFT JOIN paper_monitoring_outcomes o ON o.reservation_id=r.id WHERE o.reservation_id IS NULL').fetchone())
        with patch.object(transport.os.environ,'get',side_effect=AssertionError('no credentials')),patch.object(transport,'build_opener',side_effect=AssertionError('no transport')):
            with self.assertRaises(transport.PaperReadError) as caught:source.rpc('getSlot',[{'commitment':'finalized'}],timeout_seconds=3)
        self.assertEqual(caught.exception.code,'MONITORING_REQUEST_BUDGET_EXHAUSTED')
        self.assertEqual(list(source.attempt_evidence_refs),refs[-18:])

    def test_reused_monitoring_source_failure_after18_still_retains_mandatory_outcome(self):
        fixture,source,opener=self.monitoring_fixture()
        with patch.object(transport.os.environ,'get',return_value='SYNTHETIC_TEST_ONLY'),patch.object(transport,'build_opener',return_value=opener):
            for _ in range(18):source.rpc('getSlot',[{'commitment':'finalized'}],timeout_seconds=3)
            class BadOpener:
                def open(self,request,*,timeout):return Response(b'not JSON')
            with patch.object(transport,'build_opener',return_value=BadOpener()):
                with self.assertRaises(transport.PaperReadError) as caught:source.rpc('getSlot',[{'commitment':'finalized'}],timeout_seconds=3)
        self.assertNotEqual(caught.exception.code,'OUTCOME_PERSISTENCE_FAILED')
        key=caught.exception.evidence_hash
        self.assertEqual(source.attempt_evidence_refs[-1],key);self.assertEqual(len(source.attempt_evidence_refs),18)
        with fixture.store.connect() as c:
            self.assertEqual(c.execute('SELECT evidence_hash FROM paper_monitoring_outcomes WHERE reservation_id=19').fetchone(),(key,))
            self.assertEqual(c.execute('SELECT COUNT(*) FROM paper_monitoring_reservations').fetchone()[0],19)
            self.assertEqual(c.execute('SELECT COUNT(*) FROM paper_monitoring_outcomes').fetchone()[0],19)
        self.assertIsNotNone(fixture.store.load(key)['failure_code'])
        self.assertEqual(fixture.progress.admission(fixture.scan)['requests_used'],0)
